import { createActionGroup, emptyProps, props } from '@ngrx/store';
import { Pipeline, TransformStep, PipelineRun, SchemaField } from '@proto/api-interfaces';

export const PipelinesActions = createActionGroup({
  source: 'Transformation API',
  events: {
    'Select Pipeline': props<{ selectedId: string }>(),
    'Reset Selected Pipeline': emptyProps(),
    'Reset Pipelines': emptyProps(),
    'Load Pipelines': emptyProps(),
    'Load Pipelines Success': props<{ pipelines: Pipeline[] }>(),
    'Load Pipelines Failure': props<{ error: any }>(),
    'Load Pipeline': props<{ pipelineId: string }>(),
    'Load Pipeline Success': props<{ pipeline: Pipeline }>(),
    'Load Pipeline Failure': props<{ error: any }>(),
    'Create Pipeline': props<{ pipeline: Pipeline }>(),
    'Create Pipeline Success': props<{ pipeline: Pipeline }>(),
    'Create Pipeline Failure': props<{ error: any }>(),
    'Update Pipeline': props<{ pipeline: Pipeline }>(),
    'Update Pipeline Success': props<{ pipeline: Pipeline }>(),
    'Update Pipeline Failure': props<{ error: any }>(),
    'Delete Pipeline': props<{ pipeline: Pipeline }>(),
    'Delete Pipeline Success': props<{ pipeline: Pipeline }>(),
    'Delete Pipeline Failure': props<{ error: any }>(),
    'Run Pipeline': props<{ pipelineId: string }>(),
    'Run Pipeline Success': props<{ run: PipelineRun }>(),
    'Run Pipeline Failure': props<{ error: any }>(),
    'Run Status Update': props<{ run: PipelineRun }>(),
    'Load Preview': props<{ pipelineId: string }>(),
    'Load Preview Success': props<{ preview: SchemaField[] }>(),
    'Load Preview Failure': props<{ error: any }>(),
    'Load Runs': props<{ pipelineId: string }>(),
    'Load Runs Success': props<{ runs: PipelineRun[] }>(),
    'Load Runs Failure': props<{ error: any }>(),
    'Create Step': props<{ step: TransformStep }>(),
    'Create Step Success': props<{ step: TransformStep }>(),
    'Create Step Failure': props<{ error: any }>(),
    'Update Step': props<{ step: TransformStep }>(),
    'Update Step Success': props<{ step: TransformStep }>(),
    'Update Step Failure': props<{ error: any }>(),
    'Delete Step': props<{ step: TransformStep }>(),
    'Delete Step Success': props<{ step: TransformStep }>(),
    'Delete Step Failure': props<{ error: any }>(),
    'Reorder Step': props<{ stepId: string; newOrder: number }>(),
    'Reorder Step Success': props<{ step: TransformStep }>(),
    'Reorder Step Failure': props<{ error: any }>(),
  },
});
