/**
 * Centralized selectors for E2E tests
 * Using data-testid pattern where possible, with fallbacks to semantic selectors
 */

export const SELECTORS = {
  // Common
  common: {
    loadingSpinner: '[data-testid="loading-spinner"], .spinner, .loading',
    errorMessage: '[data-testid="error-message"], .error-message, [role="alert"]',
    successMessage: '[data-testid="success-message"], .success-message',
    modal: '[data-testid="modal"], .dialog, [role="dialog"]',
    modalClose: '[data-testid="modal-close"], .close-btn, button:has-text("Close")',
    confirmButton: 'button:has-text("Confirm"), button:has-text("Yes"), button:has-text("OK")',
    cancelButton: 'button:has-text("Cancel"), button:has-text("No")',
    saveButton: 'button:has-text("Save")',
    deleteButton: 'button:has-text("Delete")',
    editButton: 'button:has-text("Edit"), button:has-text("Configure")',
  },

  // Login page
  login: {
    container: '[data-testid="login-container"]',
    emailInput: '[data-testid="email-input"], input[type="email"], input[name="email"]',
    passwordInput: '[data-testid="password-input"], input[type="password"], input[name="password"]',
    submitButton: '[data-testid="sign-in-button"], button[type="submit"], button:has-text("Sign In")',
    errorMessage: '[data-testid="login-error"], .error-message, [role="alert"]',
    forgotPassword: 'a:has-text("Forgot")',
  },

  // Header
  header: {
    logo: '[data-testid="logo"], .logo',
    userMenu: '[data-testid="user-menu"], .user-menu',
    logoutButton: 'button:has-text("Logout"), button:has-text("Sign Out")',
    themeToggle: '[data-testid="theme-toggle"], ui-theme-toggle',
  },

  // Navigation
  nav: {
    sidebar: '[data-testid="sidebar"], .sidebar, aside',
    menuItem: (name: string) => `[data-testid="nav-${name}"], a:has-text("${name}")`,
  },

  // Filter chips
  filters: {
    chip: (label: string) => `[data-testid="filter-${label}"], ui-filter-chip:has-text("${label}")`,
    activeChip: '.active, [data-active="true"]',
  },

  // Lists
  list: {
    container: '[data-testid="list"], .list, ul',
    item: (name: string) => `[data-testid="list-item-${name}"], li:has-text("${name}")`,
    emptyState: '[data-testid="empty-state"], .empty-state',
  },

  // Forms
  form: {
    field: (label: string) => `input[aria-label="${label}"], input[placeholder*="${label}"], label:has-text("${label}") + input`,
    select: (label: string) => `select[aria-label="${label}"], label:has-text("${label}") + select`,
    textarea: (label: string) => `textarea[aria-label="${label}"], label:has-text("${label}") + textarea`,
    checkbox: (label: string) => `input[type="checkbox"][aria-label="${label}"], label:has-text("${label}") input[type="checkbox"]`,
  },

  // Ingress specific
  ingress: {
    app: '[data-testid="ingress-app"]',
    sourceListPanel: '[data-testid="sources-list-panel"]',
    sourceList: '[data-testid="sources-list"], [data-testid="source-list-panel"]',
    sourceCard: (id: string) => `[data-testid="source-card-${id}"]`,
    sourceCardByName: (name: string) => `[data-source-name="${name}"]`,
    sourceName: '[data-testid="source-name"]',
    sourceStatus: '[data-testid="source-status"]',
    sourceMetrics: '[data-testid="source-metrics"]',
    syncInfo: '[data-testid="sync-info"]',
    statsBar: '[data-testid="sources-stats-bar"]',
    filterBar: '[data-testid="sources-filter-bar"]',
    newSourceButton: '[data-testid="new-source-button"], button:has-text("New Source")',
    sourceDetail: '[data-testid="source-detail"]',
    sourceForm: '[data-testid="source-form-modal"]',
    deleteConfirmDialog: '[data-testid="delete-confirm-dialog"]',
    testConnectionButton: 'button:has-text("Test Connection")',
    syncButton: 'button:has-text("Sync")',
  },

  // Transformation specific
  transformation: {
    app: '[data-testid="transformation-app"]',
    pipelineListPanel: '[data-testid="pipelines-list-panel"]',
    pipelineSidebar: '[data-testid="pipeline-sidebar"]',
    pipelineList: '[data-testid="pipeline-list"], [data-testid="pipelines-list"]',
    pipelineSearchInput: '[data-testid="pipeline-search-input"]',
    pipelineItem: (id: string) => `[data-testid="pipeline-item-${id}"]`,
    pipelineItemByName: (name: string) => `[data-pipeline-name="${name}"]`,
    pipelineHeader: '[data-testid="pipeline-header"]',
    pipelineName: '[data-testid="pipeline-name"]',
    pipelineStatus: '[data-testid="pipeline-status"]',
    pipelineStats: '[data-testid="pipeline-stats"]',
    pipelineActions: '[data-testid="pipeline-actions"]',
    newPipelineButton: '[data-testid="new-pipeline-button"], button:has-text("New Pipeline")',
    runPipelineButton: '[data-testid="run-pipeline-button"]',
    editPipelineButton: '[data-testid="edit-pipeline-button"]',
    deletePipelineButton: '[data-testid="delete-pipeline-button"]',
    runHistoryButton: '[data-testid="run-history-button"]',
    canvas: '[data-testid="pipeline-canvas"], [data-testid="canvas-container"]',
    emptyCanvas: '[data-testid="empty-canvas"]',
    addStepPanel: '[data-testid="add-step-panel"]',
    stepTypeButtons: '[data-testid="step-type-buttons"]',
    addFilterStep: '[data-testid="add-filter-step"]',
    addMapStep: '[data-testid="add-map-step"]',
    addAggregateStep: '[data-testid="add-aggregate-step"]',
    addJoinStep: '[data-testid="add-join-step"]',
    addSortStep: '[data-testid="add-sort-step"]',
    addDedupeStep: '[data-testid="add-dedupe-step"]',
    node: (id: string) => `[data-testid="node-${id}"]`,
    nodeByType: (type: string) => `[data-node-type="${type}"]`,
    nodeName: '[data-testid="node-name"]',
    nodeType: '[data-testid="node-type"]',
    nodeRecordCount: '[data-testid="node-record-count"]',
    zoomControls: '[data-testid="zoom-controls"]',
  },

  // Reporting specific
  reporting: {
    app: '[data-testid="reporting-app"]',
    dashboardsSidebar: '[data-testid="dashboards-sidebar"]',
    dashboardsList: '[data-testid="dashboards-list"], [data-testid="dashboards-list-sidebar"]',
    dashboardItem: (id: string) => `[data-testid="dashboard-item-${id}"]`,
    dashboardItemByName: (name: string) => `[data-dashboard-name="${name}"]`,
    dashboardName: '[data-testid="dashboard-name"]',
    dashboardMeta: '[data-testid="dashboard-meta"]',
    dashboardContent: '[data-testid="dashboard-content"]',
    dashboardViewer: '[data-testid="dashboard-viewer"]',
    dashboardLoading: '[data-testid="dashboards-loading"]',
    dashboardEmpty: '[data-testid="dashboards-empty"], [data-testid="dashboard-empty"]',
    newDashboardButton: '[data-testid="new-dashboard-button"], button:has-text("New Dashboard")',
    createDashboardDialog: '[data-testid="create-dashboard-dialog"]',
    dateFilter: (range: string) => `[data-testid="date-filter-${range}"]`,
    metricsGrid: '[data-testid="metrics-grid"]',
    metricWidget: (id: string) => `[data-testid="metric-widget-${id}"]`,
    widgetGrid: '[data-testid="widget-grid"]',
    chartWidget: (id: string) => `[data-testid="chart-widget-${id}"]`,
    widgetLoading: '[data-testid="widget-loading"]',
    lineChart: '[data-testid="line-chart"]',
    barChart: '[data-testid="bar-chart"]',
    pieChart: '[data-testid="pie-chart"]',
    dataTable: '[data-testid="data-table"]',
  },

  // Export specific
  export: {
    app: '[data-testid="export-app"]',
    header: '[data-testid="export-header"]',
    viewToggle: '[data-testid="view-toggle"]',
    viewJobsButton: '[data-testid="view-jobs-button"]',
    viewScheduleButton: '[data-testid="view-schedule-button"]',
    newExportButton: '[data-testid="new-export-button"], button:has-text("New Export")',
    jobsListPanel: '[data-testid="jobs-list-panel"]',
    jobsList: '[data-testid="jobs-list"]',
    emptyJobsList: '[data-testid="empty-jobs-list"]',
    summaryMetrics: '[data-testid="summary-metrics"]',
    metricDone: '[data-testid="metric-done"]',
    metricActive: '[data-testid="metric-active"]',
    metricSize: '[data-testid="metric-size"]',
    filtersBar: '[data-testid="filters-bar"]',
    statusFilter: (status: string) => `[data-testid="status-filter-${status}"]`,
    formatFilter: (format: string) => `[data-testid="format-filter-${format}"]`,
    jobItem: (id: string) => `[data-testid="job-item-${id}"]`,
    jobCard: (id: string) => `[data-testid="job-card-${id}"]`,
    jobCardByName: (name: string) => `[data-job-name="${name}"]`,
    jobName: '[data-testid="job-name"]',
    jobQuery: '[data-testid="job-query"]',
    jobFormat: '[data-testid="job-format"]',
    jobStatus: '[data-testid="job-status"]',
    jobProgressSection: '[data-testid="job-progress-section"]',
    jobProgressBar: '[data-testid="job-progress-bar"]',
    jobProgressPercent: '[data-testid="job-progress-percent"]',
    jobDetailPanel: '[data-testid="job-detail-panel"]',
    jobDetail: '[data-testid="job-detail"]',
    scheduleView: '[data-testid="schedule-view"]',
    formatStats: '[data-testid="format-stats"]',
    recentActivity: '[data-testid="recent-activity"]',
    downloadButton: 'button:has-text("Download")',
    cancelButton: 'button:has-text("Cancel")',
  },

  // Users specific
  users: {
    app: '[data-testid="users-app"]',
    header: '[data-testid="users-header"]',
    content: '[data-testid="users-content"]',
    tabNavigation: '[data-testid="tab-navigation"]',
    tabUsers: '[data-testid="tab-users"]',
    tabCompanies: '[data-testid="tab-companies"]',
    tabRoles: '[data-testid="tab-roles"]',
    tabAudit: '[data-testid="tab-audit"]',
    inviteUserButton: '[data-testid="invite-user-button"], button:has-text("Invite User")',
    usersLayout: '[data-testid="users-layout"]',
    usersPanel: '[data-testid="users-panel"]',
    statsBar: '[data-testid="stats-bar"]',
    searchUsersInput: '[data-testid="search-users-input"]',
    companyFilterSelect: '[data-testid="company-filter-select"]',
    roleFilterChips: '[data-testid="role-filter-chips"]',
    roleFilter: (role: string) => `[data-testid="role-filter-${role}"]`,
    usersList: '[data-testid="users-list"], [data-testid="users-list-rows"]',
    usersListHeader: '[data-testid="users-list-header"]',
    emptyUsersList: '[data-testid="empty-users-list"]',
    userRow: (id: string) => `[data-testid="user-row-${id}"]`,
    userRowByEmail: (email: string) => `[data-user-email="${email}"]`,
    userName: '[data-testid="user-name"]',
    userEmail: '[data-testid="user-email"]',
    userRoleBadge: '[data-testid="user-role-badge"]',
    userStatus: '[data-testid="user-status"]',
    userLastLogin: '[data-testid="user-last-login"]',
    userDetailsPanel: '[data-testid="user-details-panel"]',
    userDetails: '[data-testid="user-details"]',
    userFormModal: '[data-testid="user-form-modal"]',
    deleteUserDialog: '[data-testid="delete-user-dialog"]',
    companiesLayout: '[data-testid="companies-layout"]',
    companiesPanel: '[data-testid="companies-panel"]',
    addCompanyButton: '[data-testid="add-company-button"], button:has-text("Add"))',
    companiesList: '[data-testid="companies-list"]',
    companyDetailsPanel: '[data-testid="company-details-panel"]',
    companyDetails: '[data-testid="company-details"]',
    companyFormModal: '[data-testid="company-form-modal"]',
    deleteCompanyDialog: '[data-testid="delete-company-dialog"]',
    rolesTab: '[data-testid="roles-tab"]',
    auditTab: '[data-testid="audit-tab"]',
  },

  // Portal/Dashboard specific
  portal: {
    featureGrid: '[data-testid="feature-grid"]',
    featureCard: (id: string) => `[data-testid="feature-${id}"]`,
    healthGrid: '[data-testid="health-grid"], .health-grid',
    serviceCard: (name: string) => `[data-testid="service-${name}"], .service-card:has-text("${name}")`,
    refreshButton: 'button:has-text("Refresh")',
    statusIndicator: '[data-testid="status-indicator"], .status-indicator',
  },
} as const;
